_target_: hadml.models.cgan.multihadron_event_gan.MultiHadronEventGANModule
noise_dim: 4
loss_type: "bce"
r1_reg: 3000
target_gumbel_temp: 0.30
gumbel_softmax_hard: True

generator: 
  _target_: hadml.models.components.encoder_transformer.Generator
  pid_map_filepath: "${datamodule.data_dir}/processed/${datamodule.pid_map_file}"
  noise_dim: ${model.noise_dim}

discriminator: 
  _target_: hadml.models.components.encoder_transformer.Discriminator
  pid_map_filepath: "${datamodule.data_dir}/processed/${datamodule.pid_map_file}"

optimizer_generator:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001

optimizer_discriminator:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001