_target_: hadml.models.cgan.multihadron_event_gan.MultiHadronEventGANModule
generator: hadml.models.components.decoder_transformer.DecoderTransformer
discriminator: hadml.models.components.decoder_transformer.DecoderTransformer
noise_dim: 4