_target_: hadml.datamodules.gan_datamodule.ParticleGANDataModule
batch_size: 128
num_workers: 4
pin_memory: False
core_dataset:
  _target_: hadml.datamodules.components.herwig.Herwig
  data_dir: "${paths.data_dir}Herwig"
  train_val_test_split: [0.96, 0.02, 0.02]
